mysqld

diff --git a/.github/workflows/dev-cicd-aws.yaml b/.github/workflows/dev-cicd-aws.yaml
--- a/.github/workflows/dev-cicd-aws.yaml
+++ b/.github/workflows/dev-cicd-aws.yaml
@@ -1,11 +1,10 @@
-name: istory ci/cd pipeline223
+name: istory ci/cd pipeline22
 
 on:
   push:
     branches: [ "develop" ]
   pull_request:
     branches: [ "develop" ]
-
 jobs:
   verify-pipeline:
     environment: runner
@@ -30,68 +29,63 @@ jobs:
           --health-timeout=5s
           --health-retries=3
     steps:
-      - name: Source Code Checkout
-        uses: actions/checkout@v4 
+    - name: Source Code Checkout
+      uses: actions/checkout@v4 
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-          
-      - name: change application.yml
-        run: |
-          cat > src/main/resources/application.yml << EOF
-          spring:
-            datasource:
-              url: ${{ secrets.DATABASE_URL }} # 예jdbc:mysql://localhost:3306/istory
-              username: ${{ secrets.MYSQL_USER }}
-              password: ${{ secrets.MYSQL_PASSWORD }}
-              driver-class-name: com.mysql.cj.jdbc.Driver
-            jpa:
-              database-platform: org.hibernate.dialect.MySQL8Dialect
-              hibernate:
-                ddl-auto: update
-              show-sql: true
-            application:
-              name: USER-SERVICE
-            jwt:
-              issuer: user@gmail.com
-              secret_key: study-springboot
-          management:
-            endpoints:
-              web:
-                exposure:
-                  include: health,info
-            endpoint:
-              health:
-                show-details: always
-          EOF
+    - name: Set up JDK 17
+      uses: actions/setup-java@v4
+      with:
+        java-version: '17'
+        distribution: 'temurin'
+    - name: Run test java
+      run: ./gradlew test
 
-      - name: Run test java
-        run: ./gradlew test
+    - name: Notify on Failure
+      if: failure()
+      run: |
+        echo "Tests failed! Pipeline will be stopped."
+        exit 1
 
-      - name: Notify on Failure
-        if: failure()
-        run: |
-          echo "Tests failed! Pipeline will be stopped."
-          exit 1
+    - name: Upload Test Report
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-report
+        path: |                    # 여러 경로 지정
+          **/build/reports/tests/test/
+          **/build/test-results/test/
+        retention-days: 30 
 
-      - name: Upload Test Report
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-report
-          path: |                    # 여러 경로 지정
-            **/build/reports/tests/test/
-            **/build/test-results/test/
-          retention-days: 30 
+    - name: Generate Basic Info in Markdown
+      run: |
+        echo "## 워크플로우 실행 정보 요약" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 담당자: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 이벤트: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 저장소: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 브랜치: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
 
-      - name: 기본수행정보 Step Summary에 표
-        run: |
-          echo "## 워크플로우 실행 정보 요약" >> $GITHUB_STEP_SUMMARY
-          echo "" >> $GITHUB_STEP_SUMMARY
-          echo "* 실행 담당자: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
-          echo "* 실행 이벤트: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
-          echo "* 실행 저장소: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
-          echo "* 실행 브랜치: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
+    - name: 코드 컨벤션 규칙 검사
+      run: |
+        mkdir -p build/reports/checkstyle
+        ./gradlew checkstyleMain checkstyleTest --info
+        ls -la build/reports/checkstyle || true
+
+    - name: 코드 컨벤션 검사 결과 업로드
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: checkstyle-report
+        path: build/reports/checkstyle/
+        retention-days: 14
+
+    - name: Generate list using Markdown
+      run: |
+        echo "## 코드 스타일 분석결과" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        if [ -f build/reports/checkstyle/main.xml ]; then # 소스분석결과 존재시
+          echo "### 소스분석결과" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          cat build/reports/checkstyle/main.xml >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+        fi
