add mysql

diff --git a/.github/workflows/dev-cicd-aws.yaml b/.github/workflows/dev-cicd-aws.yaml
--- a/.github/workflows/dev-cicd-aws.yaml
+++ b/.github/workflows/dev-cicd-aws.yaml
@@ -2,9 +2,10 @@ name: istory ci/cd dev pipeline
 
 on:
   push:
-    branches: [ "develop"]
+    branches: [ "develop" ]
   pull_request:
-    branches: [ "develop"]
+    branches: [ "develop" ]
+
 jobs:
   verify_pipeline:
     environment: runner
@@ -30,16 +31,16 @@ jobs:
           --health-retries=3
 
     steps:
-    - name: 소스코드 다운로드
-      uses: actions/checkout@v4 
+      - name: 소스코드 다운로드
+        uses: actions/checkout@v4 
 
-    - name: JDK 17 설치
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
+      - name: JDK 17 설치
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
         
-    - name: change application.yml
+      - name: change application.yml
         run: |
           cat > src/main/resources/application.yml << EOF
           spring:
@@ -67,21 +68,22 @@ jobs:
               health:
                 show-details: always
           EOF
-    - name: 테스트 수행
-      run: ./gradlew test
 
-    - name: 테스트 검사 후 실패 시 파이프라인 중단
-      if: failure()
-      run: |
-        echo "Tests failed! Pipeline will be stopped."
-        exit 1
+      - name: 테스트 수행
+        run: ./gradlew test
 
-    - name: 테스트 결과를 STEP Summary 에 업로드
-      if: always()
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-report
-        path: |                    # 여러 경로 지정
-          **/build/reports/tests/test/
-          **/build/test-results/test/
-        retention-days: 30 
+      - name: 테스트 검사 후 실패 시 파이프라인 중단
+        if: failure()
+        run: |
+          echo "Tests failed! Pipeline will be stopped."
+          exit 1
+
+      - name: 테스트 결과를 STEP Summary 에 업로드
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-report
+          path: |                    # 여러 경로 지정
+            **/build/reports/tests/test/
+            **/build/test-results/test/
+          retention-days: 30
