add mysql

diff --git a/.github/workflows/dev-cicd-aws.yaml b/.github/workflows/dev-cicd-aws.yaml
--- a/.github/workflows/dev-cicd-aws.yaml
+++ b/.github/workflows/dev-cicd-aws.yaml
@@ -1,25 +1,23 @@
- name: istory ci/cd pipeline
+name: istory ci/cd pipeline
 
 on:
   push:
-    branches: [ "develop" ]
+    branches:
+      - develop
   pull_request:
-    branches: [ "develop" ]
+    branches:
+      - develop
+
 jobs:
   verify-pipeline:
-    environment: runner
     runs-on: ubuntu-latest
     services:
       mysql:
         image: mysql:8.0
         env:
-          # root 계정 비밀번호
           MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
-          # 사용자 계정
           MYSQL_USER: ${{ secrets.MYSQL_USERNAME }}
-          # 사용자 계정 비밀번호
           MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
-          # 사용자 계정 데이터베이스
           MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
         ports:
           - 3306:3306
@@ -29,29 +27,30 @@ jobs:
           --health-timeout=5s
           --health-retries=3
     steps:
-    - name: Source Code Checkout
-      uses: actions/checkout@v4 
+      - name: Source Code Checkout
+        uses: actions/checkout@v4
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-    - name: Run test java
-      run: ./gradlew test
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-    - name: Notify on Failure
-      if: failure()
-      run: |
-        echo "Tests failed! Pipeline will be stopped."
-        exit 1
+      - name: Run test java
+        run: ./gradlew test
 
-    - name: 테스트 결과를 STEP Summary에 업로드
-      if: always()
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-report
-        path: |                    # 여러 경로 지정
-          **/build/reports/tests/test/
-          **/build/test-results/test/
-        retention-days: 30 
+      - name: Notify on Failure
+        if: failure()
+        run: |
+          echo "Tests failed! Pipeline will be stopped."
+          exit 1
+
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-report
+          path: |
+            **/build/reports/tests/test/
+            **/build/test-results/test/
+          retention-days: 30
