add mysql4

diff --git a/.github/workflows/dev-cicd-aws.yaml b/.github/workflows/dev-cicd-aws.yaml
--- a/.github/workflows/dev-cicd-aws.yaml
+++ b/.github/workflows/dev-cicd-aws.yaml
@@ -2,9 +2,10 @@ name: istory ci/cd pipeline
 
 on:
   push:
-    branches: [ "develop","main" ]
+    branches: [ "develop", "main" ]
   pull_request:
-    branches: [ "develop","main" ]
+    branches: [ "develop", "main" ]
+
 jobs:
   verify-pipeline:
     environment: runner
@@ -29,66 +30,68 @@ jobs:
           --health-timeout=5s
           --health-retries=3
     steps:
-    - name: Source Code Checkout
-      uses: actions/checkout@v4 
+      - name: Source Code Checkout
+        uses: actions/checkout@v4 
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-    - name: change application.yml
-      run: |
-        cat > src/main/resources/application.yml << EOF
-        spring:
-          datasource:
-            url: ${{ secrets.DATABASE_URL }} # 예dbc:mysql://localhost:3306/istory
-            username: ${{ secrets.MYSQL_USER }}
-            password: ${{ secrets.MYSQL_PASSWORD }}
-            driver-class-name: com.mysql.cj.jdbc.Driver
-          jpa:
-            database-platform: org.hibernate.dialect.MySQL8Dialect
-            hibernate:
-              ddl-auto: update
-            show-sql: true
-          application:
-            name: USER-SERVICE
-          jwt:
-            issuer: user@gmail.com
-            secret_key: study-springboot
-        management:
-          endpoints:
-            web:
-              exposure:
-                include: health,info
-          endpoint:
-            health:
-              show-details: always
-        EOF
-    - name: Run test java
-      run: ./gradlew test
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          
+      - name: change application.yml
+        run: |
+          cat > src/main/resources/application.yml << EOF
+          spring:
+            datasource:
+              url: ${{ secrets.DATABASE_URL }} # 예jdbc:mysql://localhost:3306/istory
+              username: ${{ secrets.MYSQL_USER }}
+              password: ${{ secrets.MYSQL_PASSWORD }}
+              driver-class-name: com.mysql.cj.jdbc.Driver
+            jpa:
+              database-platform: org.hibernate.dialect.MySQL8Dialect
+              hibernate:
+                ddl-auto: update
+              show-sql: true
+            application:
+              name: USER-SERVICE
+            jwt:
+              issuer: user@gmail.com
+              secret_key: study-springboot
+          management:
+            endpoints:
+              web:
+                exposure:
+                  include: health,info
+            endpoint:
+              health:
+                show-details: always
+          EOF
 
-    - name: Notify on Failure
-      if: failure()
-      run: |
-        echo "Tests failed! Pipeline will be stopped."
-        exit 1
+      - name: Run test java
+        run: ./gradlew test
 
-    - name: Upload Test Report
-      if: always()
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-report
-        path: |                    # 여러 경로 지정
-          **/build/reports/tests/test/
-          **/build/test-results/test/
-        retention-days: 30 
+      - name: Notify on Failure
+        if: failure()
+        run: |
+          echo "Tests failed! Pipeline will be stopped."
+          exit 1
 
-    - name: Generate Basic Info in Markdown
-      run: |
-        echo "## 워크플로우 실행 정보 요약" >> $GITHUB_STEP_SUMMARY
-        echo "" >> $GITHUB_STEP_SUMMARY
-        echo "* 실행 담당자: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
-        echo "* 실행 이벤트: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
-        echo "* 실행 저장소: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
-        echo "* 실행 브랜치: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
+      - name: Upload Test Report
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-report
+          path: |                    # 여러 경로 지정
+            **/build/reports/tests/test/
+            **/build/test-results/test/
+          retention-days: 30 
+
+      - name: Generate Basic Info in Markdown
+        run: |
+          echo "## 워크플로우 실행 정보 요약" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "* 실행 담당자: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
+          echo "* 실행 이벤트: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
+          echo "* 실행 저장소: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
+          echo "* 실행 브랜치: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
